version: "3.8"
services:
  mysql_db:
    image: mysql:latest
    volumes:
      - ./mysql/vol:/var/lib/mysql
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_USER: "${MYSQL_ROOT_USER}"
      MYSQL_DATABASE: "${MYSQL_DB}"
    ports:
      - 3306:3306
  mongodb:
    image: mongo:latest
    volumes:
      - ./mongodb/vol:/data/db
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - 8081:8081
